### ISSUE TITLE
Multi-purpose "missing" concept needed

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#10]
We need to implement a "missing" concept that can handle multiple reasons for something being "missing".

The original design was something like:

``` python
meta['columns']['q1']['values'] = [
    {'value':'1',  'text':''},
    {'value':'2',  'text':''},
    {'value':'3',  'text':''},
    {'value':'99',  'text':'', 'missing': True}
]
```

But this doesn't cater for more than 1 type of missing. Something like this would be better:

``` python
meta['columns']['q1']['values'] = [
    {'value':'1',  'text':''},
    {'value':'2',  'text':'', 'missing': ['skipped']},
    {'value':'3',  'text':'', 'missing': ['not asked']'},
    {'value':'99',  'text':'', 'missing': ['skipped', 'not asked']}
]
```

This would allow space for multiple reasons for a value being missing, and for those reasons to be overlapping with each other on any given value.

**Comment by alextanski** [comment]
Outdated.
