### ISSUE TITLE
Extend AutoSlide functionality

### ISSUE THREAD

**Issue by AndersFreund** [Quantipy/quantipy#1035]
- Add support for more chart types
- Add option to have more than one chart type and/or a table on one slide, differentiated per category type. E.g. 'basic', 'basic+nets', 'basic+nets_table', 'basic+nets_table+means', 'basic+means-line'

**Comment by jamesrkg** [comment]
@AndersFreund this ticket is a bit old is the work you're doing directly related to this issue?

**Comment by AndersFreund** [comment]
@jamesrkg Sorry, yes it is.
