### ISSUE TITLE
Batch filters: Save index (slices) instead of stored complex logics

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#1063]
Serializing to `json` is breaking the QP logical expressions, as complex objects are not supported. If we switch to simply storing the current dataframe index slice the filter targets, the `Batch` class would become more versatile and cleaner.

**Comment by alextanski** [comment]
We should adjust the private function `_manifest_filters()` in `DataSet.from_batch()` to use the index slice then.

**Comment by alextanski** [comment]
We can then even make `extend_filter()` work on a loaded Batch, by dropping from the stored index value list, etc.

**Comment by alextanski** [comment]
@nitsrek Can you make this a priority please?

**Comment by nitsrek** [comment]
see #1085
