### ISSUE TITLE
cannot import name getargspec

### ISSUE THREAD

**Issue by MegaJT** [Quantipy/quantipy#1072]
Hi,
I am new into Python. I want to do data processing using quantipy.
I tried to install Quantipy into my computer. but when i run the "import quantipy as qp" the console gives some error.

ImportError: cannot import name getargspec

import quantipy as qp
Traceback (most recent call last):

  File "<ipython-input-2-e53d58d89627>", line 1, in <module>
    import quantipy as qp

  File "C:\Users\JIJO\Anaconda2\envs\env_Quantipy\lib\site-packages\quantipy\__init__.py", line 3, in <module>
    from quantipy.core.dataset import DataSet

  File "C:\Users\JIJO\Anaconda2\envs\env_Quantipy\lib\site-packages\quantipy\core\dataset.py", line 21, in <module>
    from quantipy.core.tools.qp_decorators import *

  File "C:\Users\JIJO\Anaconda2\envs\env_Quantipy\lib\site-packages\quantipy\core\tools\qp_decorators.py", line 2, in <module>
    from decorator import (decorator, getargspec)

ImportError: cannot import name getargspec

![image](https://user-images.githubusercontent.com/41500906/43033110-b90963f4-8ce1-11e8-9568-e7b5b375581e.png)

I have updated statsmodel also
pip install statsmodels --upgrade

![error](https://user-images.githubusercontent.com/41500906/43033125-e1d340c0-8ce1-11e8-844f-4c97a9a8e83c.jpg)

**Comment by alextanski** [comment]
@MegaJT Heya.

Two questions:

1. Did you use the *develop* branch (not the master one, that one is not relecting the current state of the lib)?
2. How did you install Quantipy?

Cheers
Alex

**Comment by alextanski** [comment]
Sorry, did not want to close.

**Comment by MegaJT** [comment]
Dear,

Let me try to answer your below questions.
Two questions:

Did you use the develop branch (not the master one, that one is not reflecting the current state of the lib)?
Not Sure about this!! Not able to relate it to anything!! sorry, me new to python.


How did you install Quantipy?
1. Installed Anaconda 3
2. Created virtual enviornment "conda create -n envqp python=2.7"
3. Installed quantipy "pip install git+https://github.com/Quantipy/quantipy.git
4. opened spyder IDE 2.7 for programming

I also ran "pip install -r requirements_dev.txt" as a part of trouble shooting (maybe i messed up the things here)

Need your help!!

**Comment by MegaJT** [comment]
I Tried the below steps again 
-------------------------------------------------------------
(base) D:\>cd D:\Python\quantipy-master
(base) D:\Python\quantipy-master>activate envqp
(envqp) D:\Python\quantipy-master>pip uninstall quantipy
Uninstalling quantipy-0.1.1:
  Would remove:
    c:\users\jijo\anaconda3\envs\envqp\lib\site-packages\quantipy.egg-link
Proceed (y/n)? y
  Successfully uninstalled quantipy-0.1.1
-------------------------------------------------------------
uninstalled Quantipy first
-------------------------------------------------------------

(envqp) D:\Python\quantipy-master>pip install -r requirements_dev.txt
Obtaining file:///D:/Python/quantipy-master (from -r requirements_dev.txt (line 4))
Requirement already satisfied: pytest in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from -r requirements_dev.txt (line 1)) (3.6.3)
Requirement already satisfied: pytest-cov in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from -r requirements_dev.txt (line 2)) (2.5.1)
Requirement already satisfied: pytest-xdist in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from -r requirements_dev.txt (line 3)) (1.22.2)
Requirement already satisfied: pandas==0.19.2 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.19.2)
Requirement already satisfied: ftfy==4.4.3 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (4.4.3)
Requirement already satisfied: xmltodict in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.11.0)
Requirement already satisfied: lxml in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (4.2.3)
Requirement already satisfied: xlsxwriter in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (1.0.5)
Requirement already satisfied: pillow in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (5.2.0)
Requirement already satisfied: prettytable in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.7.2)
Requirement already satisfied: decorator in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (4.3.0)
Requirement already satisfied: watchdog in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.8.3)
Requirement already satisfied: requests in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (2.19.1)
Requirement already satisfied: python-pptx in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.6.10)
Requirement already satisfied: six>=1.10.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (18.1.0)
Requirement already satisfied: setuptools in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (39.2.0)
Requirement already satisfied: funcsigs; python_version < "3.0" in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (1.0.2)
Requirement already satisfied: py>=1.5.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (1.5.4)
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (4.2.0)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (1.1.5)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (0.3.9)
Requirement already satisfied: pluggy<0.7,>=0.5 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest->-r requirements_dev.txt (line 1)) (0.6.0)
Requirement already satisfied: coverage>=3.7.1 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest-cov->-r requirements_dev.txt (line 2)) (4.5.1)
Requirement already satisfied: pytest-forked in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest-xdist->-r requirements_dev.txt (line 3)) (0.2)
Requirement already satisfied: execnet>=1.1 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pytest-xdist->-r requirements_dev.txt (line 3)) (1.5.0)
Requirement already satisfied: pytz>=2011k in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pandas==0.19.2->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (2018.5)
Requirement already satisfied: python-dateutil in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pandas==0.19.2->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (2.7.3)
Requirement already satisfied: numpy>=1.7.0 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from pandas==0.19.2->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (1.11.3)
Requirement already satisfied: wcwidth in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from ftfy==4.4.3->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.1.7)
Requirement already satisfied: html5lib in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from ftfy==4.4.3->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (1.0.1)
Requirement already satisfied: argh>=0.24.1 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from watchdog->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from watchdog->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.1.2)
Requirement already satisfied: PyYAML>=3.10 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from watchdog->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (3.13)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from requests->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from requests->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (2018.4.16)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from requests->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (1.23)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from requests->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (3.0.4)
Requirement already satisfied: apipkg>=1.4 in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from execnet>=1.1->pytest-xdist->-r requirements_dev.txt (line 3)) (1.5)
Requirement already satisfied: webencodings in c:\users\jijo\anaconda3\envs\envqp\lib\site-packages (from html5lib->ftfy==4.4.3->quantipy==0.1.1->-r requirements_dev.txt (line 4)) (0.5.1)
Installing collected packages: quantipy
  Running setup.py develop for quantipy
Successfully installed quantipy
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
-------------------------------------------------------------
Installed it again
Running the same example script once again.
-------------------------------------------------------------
runfile('D:/Python/Quantipy_Test.py', wdir='D:/Python')
Traceback (most recent call last):

  File "<ipython-input-4-605afde04dc0>", line 1, in <module>
    runfile('D:/Python/Quantipy_Test.py', wdir='D:/Python')

  File "C:\Users\JIJO\Anaconda3\envs\envqp\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "C:\Users\JIJO\Anaconda3\envs\envqp\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 91, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/Python/Quantipy_Test.py", line 9, in <module>
    import quantipy as qp

  File "d:\python\quantipy-master\quantipy\__init__.py", line 3, in <module>
    from quantipy.core.dataset import DataSet

  File "d:\python\quantipy-master\quantipy\core\dataset.py", line 21, in <module>
    from quantipy.core.tools.qp_decorators import *

  File "d:\python\quantipy-master\quantipy\core\tools\qp_decorators.py", line 2, in <module>
    from decorator import (decorator, getargspec)

ImportError: cannot import name getargspec

-------------------------------------------------------------
Same ERROR
-------------------------------------------------------------

**Comment by alextanski** [comment]
Thanks @MegaJT, we'll look into it.

@AlasdairE Do we need to downgrade the decorator module in this case or is this somehow already handled inside the `develop` branch (I know you told me about that a time ago)?

**Comment by AlasdairE** [comment]
@alextanski decorator should be version 4.0.2.

An update to setup.py is needed so that `pip install -r req...` installs the correct version.

@MegaJT if you downgrade decorator with something like `pip install --force-reinstall decorator==4.0.2`, you should stop seeing this import error

**Comment by MegaJT** [comment]
@alextanski  This has worked!! Thanks a lot for your support. Really appreciate.

Will close this issue
