### ISSUE TITLE
DataSet.filters() / filter variable concept

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#1085]
We would want to have the option to declare specific "filter" variables, which would simply have one category (1 = "active" or something similar). These would get the `recoded_filter` property: Currently, such variables are only generated by `DataSet.from_batch(additions={'full', 'filters'})` (using the inner private `_manifest_filters()` function). It would be good if we could have a proper method that generates such a variable from an arbitrary complex logic so it could be part of a Batch definition's variable list / could be used by the Batch class vice-versa, maybe similar to `Batch.add_filter('FILTER_VAR_NAME')`.

@AndersFreund: I am adding you as we talked about this regarding the YG  / Crunch use case. Your ideas can be collected in this ticket.

**Comment by nitsrek** [comment]
done and merged
