### ISSUE TITLE
Bug in Dataset.get_batch()

### ISSUE THREAD

**Issue by AndersFreund** [Quantipy/quantipy#1093]
get_batch() checks for existence of utf8 decoded batch name, if found it returns a qp.Batch instance with a name that is not utf8 decoded. Meaning a second version of the requested batch is added.
Last line should be **return qp.Batch(self, name.decode('utf8'))**

Link to code: https://github.com/Quantipy/quantipy/blob/develop/quantipy/core/dataset.py#L6587-L6602

def get_batch(self, name):
        """
        Get existing Batch instance from DataSet meta information.

        Parameters
        ----------
        name: str
            Name of existing Batch instance.
        """
        batches = self._meta['sets'].get('batches', {})
        check = batches.get(name.decode('utf8'))
        if not check:
            check = batches.get(name)
        if not check:
            raise KeyError('No Batch found named {}.'.format(name))
        return qp.Batch(self, name)

**Comment by nitsrek** [comment]
done and merged
