### ISSUE TITLE
Installlation query

### ISSUE THREAD

**Issue by AnkitMoody** [Quantipy/quantipy#1130]
Please suggest how can we install Quantipy package and configure with my Python.
Any specific system requirements for Quantipy?

**Comment by AnkitMoody** [comment]
Thanks @jskalant 

Can you please look at latest issue I shared today #1147

**Comment by Havlin** [comment]
@jskalant Do you know if/when there will be a quantipy version that can be installed with Python 3?

**Comment by alextanski** [comment]
We are closing inactive issues and if this still is a problem you will please need to create a new issue.
