### ISSUE TITLE
Getting List index out of range issue while reading Dimension MDD/DDF

### ISSUE THREAD

**Issue by AnkitMoody** [Quantipy/quantipy#1147]
HI, While I try to read Dimemsion data file using below code I'm getting issue as list out of index. Pls suggest.

**meta, data = read_dimensions(path_mdd, path_ddf)**

File "c:\user\anaconda2\lib\site-packages\quantipy\quantipy\core\tools\dp\dimensions\reader.py", line 539, in begin_column
    var = xml.xpath(xpath_var.decode('utf-8'))[0]

IndexError: list index out of range

**Comment by jskalant** [comment]
@AnkitMoody  Are you using the Master branch?  

Please note that @alextanski addressed a similar issue here: #994 

In a nutshell, the Master branch seems to have been coded around a specific MDD/DDF setup and @alextanski  published a new branch (i994-read_dimensions_generalized_files)  for the general MDD/DDF.

Can you please try this branch?

Cheers,

JC
