### ISSUE TITLE
Rim.add_group(): support QP logic operators 

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#1201]
We are currently limited to using string expressions suitable for `pandas.DataFrame.query()`. We then also need to remove the note in the official docs. 🦐

**Comment by nitsrek** [comment]
@jamesrkg this might be needed in our template, since qp filters are delimited sets and pd.query() does not support those. Is there a chance to prioritize this ticket?

**Comment by jamesrkg** [comment]
Yes. Just stick to the specific use case in this ticket though so as not to get too lost in possible other integrations throughout the lib. We can deal with those another time.

**Comment by alextanski** [comment]
I am doing this now. Would be embarrassing to launch template 2.0 with still non-dataset / non logic filtering inside the weight algorithms.

**Comment by alextanski** [comment]
@jamesrkg @kerstin @AndersFreund : Are you aware of any processes that use the `WeightEngine` module externally, i.e. without the rest of the QP / template infrastructure?

**Comment by alextanski** [comment]
It seems impossible to get this to work with `DataSet` and logic operators since there are so many methods that are modifying and passing around different versions of a `pd.DataFrame`.

**Comment by alextanski** [comment]
Not sure what do with this yet. I think about it over the weekend, but I guess rewriting it completely is the only option.

**Comment by alextanski** [comment]
Hey @nitsrek:
In agreement with @jamesrkg we will first "quick" & (very) dirty hack this:

1. `WeightEngine` will internally create a `DataSet` if data incl. meta is passed
2. If a passed `Rim` scheme filter contains qp-logic we are building a filter/dummy variable from it
3. We inject the filter/dummy into the `self.groups[group][self._FILTER_DEF]` as an optional key (so we need to turn this into a `dict` first).
4. Then we can `get('logical_dummy', 'org_filter')` and depending on the result either `query()` the "regular"  pandas -bassed expression (from `'org_filter'`) or inject the `logical_dummy_varname==1` expression.

After I have this done, this ticket will be closed and I will open a new one for the Rewrite of `Rim.py` and `WeightEngine.py`.

**Comment by alextanski** [comment]
To limit the amount of work needed in both `Rim` and `WeightEngine`, I have slightly refactored my initial version of this hack to work as per:

1. Dataset is constructed in `WeightEngine`
2. In `add_scheme()` a method called `_resolve_filters()` (see below) is called:
    a) Grabs the filter target variables that are needed later on from every expression type (`pandas` or qp-logical) and stores in new property of the scheme.
    b) If qp-logic: Build filter dummy, put filter dummy into weight `_df`, updates filter expression to be a `pandas` compatible str e.g. `'Group name_logic_dummy==1'`.


```
    def _resolve_filters(self, scheme):
        grps = scheme.groups
        for grp in grps:
            f = grps[grp]['filters']
            if f is not None:
                grps[grp]['filter_vars'] = self._find_filter_varables(f)
                if not isinstance(f, (str, unicode)):
                    f = self._replace_logical_filter(f, grp)
                    msg = 'Converted {} filter to logical dummy expression'
                    print msg.format(grp)
                grps[grp]['filters'] = f

    def _find_filter_varables(self, filter_expression):
        """
        """
        filter_variables = []
        print 'FOUND:', filter_expression
        for col in self._df.columns:
            if re.search(r"\b"+col+r"\b", unicode(filter_expression)):
                filter_variables.append(col)
        return filter_variables

    def _replace_logical_filter(self, filter_expression, grp_name):
        """
        """
        varname = '{}_logic_dummy'.format(grp_name)
        category = [(1, 'select', filter_expression)]
        meta = (varname, 'single', '', category)
        self.dataset.derive(*meta)
        self._df[varname] = self.dataset._data[varname].copy()
        self.dataset.drop(varname)
        return '{}==1'.format(varname)
```

**Comment by alextanski** [comment]
Tests currently failing in `test_weight_engine` as the test data for the weight module is not following our meta conventions 🤣 .

**Comment by alextanski** [comment]
@nitsrek Let's catch up on this tomorrow. There are some side effects that are relevant for the template.

**Comment by alextanski** [comment]
Closing this. Ashamed.
