### ISSUE TITLE
'NoneType' object has no attribute 'charmap_decode'

### ISSUE THREAD

**Issue by ruch0** [Quantipy/quantipy#1242]
I have tried installing Quanitpy multiple times creating a fresh environment and every time I get the error **'NoneType' object has no attribute 'charmap_decode'** .
I am simply trying to execute one of the examples codes -

`import quantipy as qp
from quantipy.core.tools.dp.prep import frange

path_csv = 'quantipy\tests\Example Data (A).csv'
dataset = qp. dataset('Example Data (A)')
dataset.read_quantipy(path_csv)

dataset.crosstab('q2', text = True)`

**Comment by alextanski** [comment]
Heya, are you running on the `staging-develop` branch? If not, please try!

Thanks
Alex

**Comment by alextanski** [comment]
Did not want to close, sorry!

**Comment by ruch0** [comment]
I installed the develop branch. However, I still keep getting this -

  **File "C:\Users\~\Python\Python27\site-packages\ftfy\bad_codecs\sloppy.py", line 127, in decode
    return codecs.charmap_decode(input, errors, decoding_table)

AttributeError: 'NoneType' object has no attribute 'charmap_decode'**

If it helps, I am trying to run this using Spyder in the environment that was created on a Windows 10 machine.

**Comment by alextanski** [comment]
Can you please check what
```import ftfy
ftfy.__version__
```

shows? Should be `'4.4.3'`

**Comment by ruch0** [comment]
ftfy version is 4.4.3. I am not sure if it was implied or not, but prefixing the **dataset.crosstab('q2', text = True)** with **print** i.e. **print dataset.crosstab('q2', text = True)** gave the desired output without generating any errors.
