### ISSUE TITLE
Possible to some kind of value count with weights?

### ISSUE THREAD

**Issue by Havlin** [Quantipy/quantipy#1258]
Pandas has a useful method called value_counts which creates a column of counts or frequency for each categorical column you give it.

Is there something in Quantipy that allows you do something similar, but with a weighted value count? I don't want a crosstab, I simply want a uni-variate column with weighted value frequencies.

**Comment by alextanski** [comment]
Heya, sorry totally missed that. Using `crosstab()` without the `y`-axis provided is not an option?

**Comment by alextanski** [comment]
bump: @Havlin  ^^

**Comment by Havlin** [comment]
Oh okay I didn't realize that worked! thanks a lot!
