### ISSUE TITLE
Chain/ChainManager: add(), insert(), add_chain() - renaming needed

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#1260]
Because these methods have similar names but are doing very very different things.

**Comment by alextanski** [comment]
also: `merge()`....

**Comment by nitsrek** [comment]
agreed new names:

*  `.add()` -> `.add_df()`
*  NEW! `.add()` see #1259 
*  `.merge()` -> `.unite_folders()`
*  `.insert()` -> `.merge()`
