### ISSUE TITLE
AttributeError: module 'quantipy' has no attribute 'Rim'

### ISSUE THREAD

**Issue by tbagnoli** [Quantipy/quantipy#1286]
Hello, I'm running Python 3.7.3 on macOS, and have installed quantipy with pip.

I was trying to follow the instruction for Rim weights in https://quantipy.readthedocs.io/en/staging-develop/sites/lib_doc/weights/02_rim.html, but I'm pretty immediately running into the following error:

```
> import quantipy as qp
> scheme = qp.Rim('my_first_scheme')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-64839714172d> in <module>
----> 1 scheme = qp.Rim('my_first_scheme')

AttributeError: module 'quantipy' has no attribute 'Rim'
```
is this no longer a feature of this package? Is there now a suitable replacement for it within quantipy?

**Comment by alextanski** [comment]
Heya @tbagnoli! `Rim` is still a part of the package.


Does  this work instead?:

```
from quantipy.core.weights.rim import Rim
scheme = qp.Rim('my_first_scheme')
```

Some other points:

1. Can you try to switch to the devleop-branch (this one is most frequently updated and used in-house)?

2. Generally, we are currently making effeorts to move QP to work with py3 but for now it's only stable in py2.7 environments.

3. There is no explicit mac-support, although I am not sure if this matters in this case. There could be a difference in how site-packages are managed on mac, but I have no experience in this area.

**Comment by tbagnoli** [comment]
Hello, thanks for answering!

Your suggested fix didn't work with the pip installation I already had:

```
from quantipy.core.weights.rim import Rim

ModuleNotFoundError: No module named 'quantipy.core'
```
I then tried your first suggestion, to install from the develop branch.
It failed because of incompatibility with python 3:

```
pip install git+git://github.com/Quantipy/quantipy.git@develop
...
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/00/5n3hxd5x14df2w2sy4bq0_8w0000gn/T/pip-install-4idwk1cn/functools32/
```

Even if you're not planning to switch to python 3 or update the documentation anytime soon, a couple of very big and loud disclaimers regarding compatibility and installing from the develop branch (unless that's what `pip install quantipy` does by default?) seem like a quick fix to add here:
https://quantipy.readthedocs.io/en/staging-develop/index.html#
and here:
https://github.com/Quantipy/quantipy
