### ISSUE TITLE
Split delimited set into N-mentions+others

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#1297]
Assuming data in a delimited set variable, _where we know the response data is ordered_, such as:

`6;56;3;40;22;21;36;1;12;43;11;18;15;17;27;25;48;57;55;62;`

It would be good to be able split the variable into N+1 new variables where N is the number of single-response mentions from the first, with all mentions beyond N ending up in a delimited set with all other responses.

This will let us transform ordered delimited set data into first/second/third/etc. mentions + other mentions.

**Comment by alextanski** [comment]
signature will be: `nfirst(ds, name, n_first=3, others='others', reduce_values=False)`

**Comment by alextanski** [comment]
Docstring not yet in, therefore parameters:

* name: the name of the delimited set.
* n_first: get the first n  mentions from the code string.
* other: naming suffix for variable name & label (label is not good, I copy and pasted from the variable name; it should be more like ` '(others)'`, also true for the mentions...). If `None`, there won't be an other-variable.
* reduce_values: drop all metadata based on `codes_in_data`, i.e. get rid of empty categories.

**Comment by alextanski** [comment]
Hell, I simply fixed the variable labels quickly.

**Comment by alextanski** [comment]
Clean-up needed, code has some smaller redundancies.

**Comment by alextanski** [comment]
all done. closed.
