### ISSUE TITLE
set_targets equivalent for setting the sample distribution 

### ISSUE THREAD

**Issue by sjgiorgi** [Quantipy/quantipy#1313]
Is there an method equivalent to `Rim.set_targets()` for setting the sample side distributions? As opposed to having them calculated from the data points in the dataframe.  

The issue is that I would like to fill in missing cells with some data, to stop the raking algorithm from failing. I realize I can create some "dummy" users in my dataframe but it would be nice to allow for non-integer data.

**Comment by alextanski** [comment]
@sjgiorgi Heya, I am not completely sure what you are trying to do. Do you want to populate empty cells with values in a way that will keep the overall (pre-imputation) sample distribution stable?

**Comment by sjgiorgi** [comment]
Correct. 

For example, if I'm adjusting for age (3 bins) and gender (male / female) and I have no males in the second age bin. I could be in a situation where *I know* I have a highly biased sample and want this cell to be non-empty. I could:

1. Add in a dummy person who I set to male and middle aged
2. Initialize the cell (or even all cells) with some non-zero value

(1) is similar to (2) in that it will initialize the cell to an integer value (the number of "dummy people" I have). But in (2) I want to initialize a cell to a non-integer value, for example, a small non-zero number like .0001 (which seems to be standard in the raking literature).

**Comment by alextanski** [comment]
Ok, I get it now. But unfortunately this is not supported in the engine.

**Comment by sjgiorgi** [comment]
After digging into the code more I realized that this wasn't possible. Would be a nice feature at some point though.
