### ISSUE TITLE
Unweighted and weighted base

### ISSUE THREAD

**Issue by dan-klasson** [Quantipy/quantipy#1318]
I can get the `rbase` and `cbase` using something like this:

```
stack = qp.Stack(add_data={'pew': {'data': dataset.data(), 
                                   'meta': dataset.meta()}})
stack.add_link(x=categorized,y=categorized,views=['cbase','c%', 'rbase', 'cbase_gross'])
stack['pew']['no_filter']['gender_']['Q1_']['x|f|:y|||rbase'].dataframe
```

But how do I get the result of both weighted and unweighted bases?

**Comment by nitsrek** [comment]
@dan-klasson `stack.add_link()` has a parameter `weights` that allows a list of weight names. In your case `[None, 'weightname']` might be the solution

**Comment by dan-klasson** [comment]
@nitsrek But that's just what variable (column) it should use no? I tried adding `weights=[None, 'weights]` but I get this:

```
Question            Q1_
Values              All
Question Values
gender_  1       2069.0
         2       1931.0
```

Shouldn't it be something I need to add on the view?

**Comment by nitsrek** [comment]
I guess you just take the wrong view_key. `x|f|:y|||rbase` is for the unweighted view and `x|f|:y||weight_a|rbase`  for the weighted view

![image](https://user-images.githubusercontent.com/20853786/72086742-bbfe1500-3307-11ea-94a0-cf4bfa43c276.png)

**Comment by dan-klasson** [comment]
@nitsrek That's it. Exactly what I was looking for. Thank you.
