### ISSUE TITLE
Significance testing 

### ISSUE THREAD

**Issue by dan-klasson** [Quantipy/quantipy#1320]
I got the significance testing working with the `crosstab2` method in the `i1216_dataset_crosstab` branch. So I tried to extract that logic so I don't have to rely on an experimental method. 

This is what I came up with. Unfortunately it's throwing in an error in `Stack.add_tests`:

```
stack = qp.Stack('pew', add_data={'pew': {'data': dataset.data(), 
                                'meta': dataset.meta()}})
view = qp.ViewMapper().make_template(
    method='coltests',
    iterators={
        'metric': ['props', 'means'],
        'mimic': ['Dim'],
        'level': [0.05]})
view.add_method(
    'significance',
    kwargs = {
        'flag_bases': [30, 100],
        'test_total': None,
        'groups': 'Tests'})
view.add_method('cbase')
stack.add_link('pew', x='gender_', y='Q1_', views=view, weights=[None, 'weight'])

#  File "/Users/danklasson/Code/foo/quantipy/quantipy/core/view_generators/view_maps.py", line 583, in _get_view_names
#    if v.split('|')[1].startswith('f')
# IndexError: list index out of range
```

Also tried using batches as per the documentation:

```
batch1 = dataset.add_batch('Batch1')
batch1.set_sigtests([0.05])
stack = dataset.populate('Batch1')
stack.add_tests(['Batch1'], verbose=False)
stack.add_link(x=categorized,y=categorized,views=['cbase','c%'], weights=[None, 'weight'])

```

```
batch1 = dataset.add_batch('Batch1')
batch1.set_sigtests([0.05])
stack.add_tests(['Batch1'], verbose=False)
stack.add_link(x=categorized,y=categorized,views=['cbase','c%'], weights=[None, 'weight'])
```

What's the right way to do this? Pointers appreciated.

**Comment by alextanski** [comment]
@dan-klasson The easy way to do this is to use the `Batch` to spec the aggregations and then use `stack = dataset.populate()` to generate the `Stack`.

After that you can use `stack.aggregate()` and pull out the results. We can produce a full example if you need one.

**Comment by alextanski** [comment]
We are aware that the qp docs are leaving a lot to be desired, but please have a look at:

https://quantipy.readthedocs.io/en/staging-develop/sites/lib_doc/batch/00_overview.html 

and 

https://quantipy.readthedocs.io/en/staging-develop/sites/lib_doc/engine/00_overview.html

as well as

https://quantipy.readthedocs.io/en/staging-develop/sites/lib_doc/engine/04_agg_methods.html#basic-views

**Comment by geirfreysson** [comment]
I've been using the below to do sigtests (although I haven't gotten `test_total` to work).
 ```   
stack = qp.Stack(name='sig', add_data={'sig': {'meta': dataset.meta(), 'data': dataset._data}})
stack.add_link(data_keys=['sig'], x='service', y='agecat', views=['c%', 'counts'], weights=['myWeight'])
link = stack['sig']['no_filter']['service']['agecat']
test = qp.Test(link, 'x|f|:||myWeight|counts')
test = test.set_params(level='mid')
test.run()
```
This will return the sigtest with the codes like so
![Screenshot 2020-01-10 11 59 21](https://user-images.githubusercontent.com/4630/72151653-a852bd00-33a0-11ea-9864-e81aebe031f3.png)

**Comment by dan-klasson** [comment]
@alextanski Yep, read that. Also tried this:

```
batch1 = dataset.add_batch('Batch1')
batch1.set_sigtests([0.05])
stack = dataset.populate('Batch1')
stack.aggregate(['counts', 'cbase'], batches=['Batch1'], verbose=False)
```

But getting:

```
File "/Users/danklasson/Code/foo/quantipy/quantipy/core/stack.py", line 1986, in aggregate
   raise ValueError(msg)
 ValueError: Cannot aggregate, 'xs' contains no valid variables.
```

@geirfreysson's way works for me though. But I have to call it in a loop. Maybe using batches is a more efficient way of doing it?

**Comment by alextanski** [comment]
Batches is the way to go. Did you use `Batch.add_downbreak()` in your setup?

**Comment by geirfreysson** [comment]
This worked for me, doing it with the batch
```
batch1 = dataset.add_batch(name='batch1')
batch1.add_downbreak('service')
batch1.add_crossbreak('agecat')
batch1.set_sigtests([0.05])
stack = dataset.populate(['batch1'])
stack.aggregate(['counts', 'cbase'], batches=['batch1'], verbose=False)
stack.add_tests(['batch1'])
stack['Customer satisfaction']['no_filter']['service']['agecat']['x|t.props.Dim.05|:|||significance']
```

![Screenshot 2020-01-10 12 50 41](https://user-images.githubusercontent.com/4630/72154174-d38cda80-33a7-11ea-8c29-ff2d6642e8d1.png)

I don't know what "*" means here, though.

**Comment by alextanski** [comment]
`*` is flagging (effective) bases below 30, `**` would flag bases below 100 in this example.

**Comment by dan-klasson** [comment]
@alextanski @geirfreysson 

That works for me too. Thanks again guys.
