### ISSUE TITLE
Ascribe coding fails if meta only has one code in code frame

### ISSUE THREAD

**Issue by AndersFreund** [Quantipy/quantipy#1338]

**Comment by AndersFreund** [comment]
This line: 
https://github.com/Quantipy/quantipy/blob/5dd5fdb66fa222d869467c9e88b30afaef3c8753/quantipy/core/tools/dp/ascribe/reader.py#L55

Usually `var['Answers']['Answer']` is a list of Dictionaries, but if only one code it returns a Dictionary.

**Comment by nitsrek** [comment]
fixed
