### ISSUE TITLE
*hmerge()* doesn't deal with dimensions grids correctly

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#150]
The function looks for all items in meta['sets']['data file'] which point to 'mask' for grids not 'columns'.

**Comment by jamesrkg** [comment]
I'll take this one.

**Comment by AlasdairE** [comment]
Great. I discovered this as I was trying to do a merge where the right dataset has new columns and ids (plus columns and ids in common).

```python
meta, data = hmerge(
    (meta, data),
    (meta_add, data_add),
    how='outer',
    on='id'
)
```

**Comment by jamesrkg** [comment]
@AlasdairE i believe this one has been resolved but i don't know by what branch - can you confirm?

**Comment by jamesrkg** [comment]
@AlasdairE i'm going to close it but can you tag the PR that resolved this one?
