### ISSUE TITLE
Migrate stack filters to quantipy logic

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#159]
Currently stack filters implement ``pd.DataFrame.query()`` but this doesn't satisfy the requirements for filtering on milti-coded questions (delimited sets) and is inconsistent with other uses of filtering (recoding and view logic). It would be better if stack filters would be given as 'complex logic' statements.

On downside to this approach will be: what will the filter key be? We could use a non-generic form of the view key conditional part, such as ``q2[{1,2}]&gender[{1}]``.

**Comment by alextanski** [comment]
Related: .query() seems to not work with the Dimensions grid slice names, due to their special characters.

**Comment by alextanski** [comment]
`DataSet.filter()` requires an `alias` alongside with the qp-logic used as the filter. We can use the `alias` (`'men / 40-60'`) as the Stack filter key?

**Comment by alextanski** [comment]
bumping this again... we will need that functionality soon!

**Comment by alextanski** [comment]
merging this into the branch related to #607

**Comment by jamesrkg** [comment]
Resolved by #607.
