### ISSUE TITLE
view notation on descriptives: wrong assumption on meta structure in View()._descriptives_relation()

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#193]
There is a wrong assumption where to find the correct value mappings in the meta document. Current structure assumes Dimensions-like variable and mask (aka Grid) naming which makes arbitrary (for example Askia) conventions fail.

Solution is to directly check the lib@values string and look for split(LIB_STRING, '@')[-1] to get the correct value object for masks/arrays.

**Comment by jamesrkg** [comment]
Resolved by #214.
