### ISSUE TITLE
Full index aggregations and simplification of stack.get_chain()

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#203]
- 1. Separate ``full_index_dataframe`` from paint_dataframe and rules application
- 2. Implement ``full_index_dataframe`` at the point of aggregation (so ``add_link()`` always returns a ``full_index_dataframe`` as your view)
- 3. This will take away reliance for rules application on an instance of a ``Link`` object, rules can be applied simply to a dataframe with reference to the rules meta

**Comment by alextanski** [comment]
I am referencing this  to #206, which is assgined to me.

**Comment by jamesrkg** [comment]
This will be resolved by #235.
