### ISSUE TITLE
Quantity(): add optional meta argument to use meta when available

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#206]
In order to speed up the chain generation process, we need to be able to force View dataframes and therefore the result of to_df() method being able to create a multindex on the 1/0 axis based on response codes found in the meta.

How to achieve this:

1. class constructor gets argument use_meta, defaulting to False
2. If True: matrix and matrix defintitons obey to the codes from the meta
3. to_df() picks up the meta-based values when constructing the multiindex

**Comment by jamesrkg** [comment]
This will be resolved by #290.
