### ISSUE TITLE
Unattended lists in wildcard logic

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#21]
In simple logic statements unattended lists are assumed to be has_any() queries. Currently this isn't true for unattended lists in wildcard logic (they fail).

We want to be able to do this:

```python
{q1_1: [1, 2]}
```

Instead of this:

```python
{q1_1: has_any([1, 2])}
```

**Comment by AlasdairE** [comment]
:+1:

**Comment by jamesrkg** [comment]
Fixed.
