### ISSUE TITLE
axis-nesting: approach via recoding, new class Nest()

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#211]
Nesting will be re-introduced using a recoding-based approach that crossed all relevant axis level categories in a new variable. Meta will be catered for. The class will provide methods to restructure the variable into multindexed representations, slice sections, instruct the recode, create the meta, etc.

**Comment by alextanski** [comment]
![image](https://cloud.githubusercontent.com/assets/13119448/13008915/be8954e8-d199-11e5-80fb-65bbe07bb1cf.png)

**Comment by jamesrkg** [comment]
Resolved by #367.
