### ISSUE TITLE
Auto meta creation for isolated dataframes

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#23]
We need an auto-meta-generation method for creating Quantipy meta for otherwise isolated dataframes.

**Comment by alextanski** [comment]
What do you mean by auto-meta? Just type-inference (num, single, multi, ...) or a full framework to automate question/value text etc.?

**Comment by alextanski** [comment]
This is already done: ``DataSet.from_components()`` is now able to build a proper meta document from an incoming ``pd.DataFrame``; `int`, `float`, `object` (string) columns are converted automatically and can the easily be converted. Closing this.
