### ISSUE TITLE
UserWarning needed if trying to use descriptives on a delimited set

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#28]
Descriptive stats (mean, median, etc.) are not support on a delimited set. At the moment this will trigger an exception in the view method but no feedback is given to the user.

Can we add a UserWarning so that the user is made aware of why their request hasn't produced a view?

**Comment by alextanski** [comment]
There is no real exception, there is a if-not-multi-then-do-it logic. Do you really want a warning for this? This would spam the console since it will print it each time a x=multi-link goes inside the view method.

**Comment by jamesrkg** [comment]
Ok, let's just leave it.
