### ISSUE TITLE
sortx fixed values that do not exist are added to a view

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#315]
For example:

``` python
meta['columns']['q11']['rules'] = {
    'x': {'sortx': {'fixed': [955, 977]}}}
```

If there is no value `955` in `q11` it will end up being added as an empty value row in the views:

![capture](https://cloud.githubusercontent.com/assets/5341764/12427167/a4ec8132-beab-11e5-82c0-d84f7f09f10f.JPG)

This bug is also the reason why the value labels do not end up being painted by the `ExcelPainter`.

**Comment by alextanski** [comment]
This is prevented using the DataSet.sorting() method. We can close this.
