### ISSUE TITLE
Implement Statistical Analysis Class in engine.py

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#327]
Name will be Multivariate. First application is Correspondence analysis (Singular value decomposition + plot).

**Comment by alextanski** [comment]
Status update, possible is:

1. Covariance
2. Correlation
3. Mass
4. Expected frequency table
5. Chi^2
6. Correspondence analysis / Inertia decomposition
7. topline Reach analysis
-------------------------------------

Next step is to connect the topline Reach with the full TURF analysis. After that: TURF using combinations/portfolios.

**Comment by alextanski** [comment]
Plots have been edited to roughly use YG colors:

Correspondence:
![image](https://cloud.githubusercontent.com/assets/13119448/13204020/49fd2b76-d8c5-11e5-9189-f72670fa2699.png)

Corr. matrix:
![image](https://cloud.githubusercontent.com/assets/13119448/13204027/62752352-d8c5-11e5-863e-7e78b14ef2ba.png)

Scatters:
![image](https://cloud.githubusercontent.com/assets/13119448/13204033/717e12aa-d8c5-11e5-9f92-d2c9d550cfa3.png)

**Comment by alextanski** [comment]
Dev is going on in the core lib, branch: **i27-DataSet_class_to_core_lib**
Also: The `Multivariate` class will be placed into the `qp.sandbox.`

**Comment by jamesrkg** [comment]
@alextanski i27 is now merged - should we leave this ticket open?

**Comment by jamesrkg** [comment]
Resolved by #463.
