### ISSUE TITLE
crosstab should concat frequency of x by default

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#360]
Using `crosstab` to check a recode can be misleading because it only shows cases where data is populated for both `x` and `y`. In order to force cases where data is populated for either `x` *or* `y` the method until now has been to use `pd.concat([f, ct], axis=1])` but this is needed commonly enough to warrant internal support by `crosstab`.

Appending the `frequency` of `x` to the `crosstab` result should become the default behaviour.

**Comment by alextanski** [comment]
Implementing tests against total links, I have added a new parameter to Quantity(), called `base_all`.
If set to True, the x-variable will be uncoditionally aggregated, so this could directly been used in crosstab().

**Comment by jamesrkg** [comment]
We'll leave `Quantity(base_all=True` for development purposes and implement this for `crosstab`, but it won't be the default behaviour.

**Comment by jamesrkg** [comment]
Resolved by #363.
