### ISSUE TITLE
matrix slicers/indexing on group() flawed

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#373]
Currently the indexing of the matrix is flawed when the meta is not following implicit assumptions about structure (e.g. ascending value codes). This can lead to hard crashes or (worse) wrong output that passes silently. As a fix, I am going to implement a new _sort_indexers_by_codes() method that handles the correct ordering in the relevant situations.

**Comment by jamesrkg** [comment]
Resolved by #374.
