### ISSUE TITLE
add textbox to highlight a continued slide

### ISSUE THREAD

**Issue by Majeed-Sahebzadha** [Quantipy/quantipy#379]
Writing text _'continued (x)'_ to a given slide's title placeholder fails when title placeholder doesn't exist. Would be a common fail since users are allowed to use their own templates. Text _'continued (x)'_ now added to the question label shape, aka header shape, which is created and added from scratch. This approach removes the need to search for certain shapes.

**Comment by jamesrkg** [comment]
Resolved by #400.
