### ISSUE TITLE
view_maps: Implement fast-route view creation for basic views and instant-% computation

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#395]
We can speed up Quantipy quite easily by defining a know_view `basics` that will generate `cbase`, `counts`, `%` and `counts_sum`/`c%_sum` in one go by computing 5 views at once. For nets, a `get_pct` kwarg can dominate over `rel_to` and create the counts and percentage version in one go.

**Comment by alextanski** [comment]
fast path resolved in branche(s): i401 / i395.
instant % will be done in a separate issue: #405

**Comment by jamesrkg** [comment]
Resolved by #420.
