### ISSUE TITLE
Parent class for Stack and Chain

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#42]
There are a lot of way stack and chain objects are similar, and a lot of utility/convenience functions that are useful for both (and not useful to much else).

Examples include the following methods:

``` python
stack.describe()
stack.verify_key_types()
stack.verify_multiple_key_types()
stack.verify_key_exists()
stack.force_key_as_list()
stack.yield_links()
stack.yield_views()
stack.reduce()
stack.save()
stack.load()
```

... and the following function (there are more....):

``` python
core.tools.view.query.get_dataframe
```

... and over time, no doubt many more.

What would be better is a new Class that defines all of these similarities and from which both Stack and Chain (and probably other 'shape' variants in the future) inherit.

**Comment by jamesrkg** [comment]
@biggihs this seems like a good fit for you, when we get to it.

**Comment by alextanski** [comment]
I guess we can close this @jamesrkg ?
