### ISSUE TITLE
Tips/tricks section in the Docs

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#43]
We'll eventually want a tips/tricks section to the docs to help users get to an advanced level using the lib.

This issue is just to compile a list of things that can end up in that part of the Docs.

**`get_index_mapper` for general data management**
Using mappers normally designed for use with `recode` for general data management purposes such as dropping/splitting dataframes.

**Comment by alextanski** [comment]
I think we have something like this now in template docs. Let's use this as a start and review this in the near future.

Closing (?)
