### ISSUE TITLE
improve_df_sorting

### ISSUE THREAD

**Issue by Majeed-Sahebzadha** [Quantipy/quantipy#444]
1. create two dataframes, a) without fixed categories (df1), b) only fixed categories (df2)
2. sort df1
3. put each df1 row as a tuple in a list
4. insert df2 rows by their original position in the list of tuples created in step 3
5. create a dataframe from the list of tuples. 

This method allows one to sort a df while preserving the position of fixed categories.

**Comment by jamesrkg** [comment]
Resolved by #451.
