### ISSUE TITLE
core: missing handling per meta and in aggregations

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#445]
This will be introduced alongside the DataSet class, see #27

**Comment by alextanski** [comment]
Dev is going on in the core lib, branch: **i27-DataSet_class_to_core_lib**

**Comment by alextanski** [comment]
Dev is going on in the core lib, branch: **i27-DataSet_class_to_core_lib**

**Comment by jamesrkg** [comment]
Resolved by #463.
