### ISSUE TITLE
gross base view methods: calculations must ignore missing flags

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#478]
With the introduction of automatic missing data handling by meta, the gross base view method will need to ignore any missing flags.

**Comment by alextanski** [comment]
Thinking about this a bit more the following should happenon a more general note:
1. Remove the `use_meta`-parameter from the `Quantity` engine. The engine should use available meta and otherwise run without it.
2. Introduce a `ignore_flags` parameter that controls how the engine(s) handle meta instructions like missing flags.

**Comment by jamesrkg** [comment]
Resolved by #482.
