### ISSUE TITLE
handle duplicate indexes when sorting df

### ISSUE THREAD

**Issue by Majeed-Sahebzadha** [Quantipy/quantipy#487]
A table with duplicate indexes caused the sorting function to crash. 

E.g. 

    Ready Steady Store    3.614764
    Big Box    0.000000
    Alligator    1.760532
    None of these    0.822068
    Don't know    38.765192
    Don't know    0.000000

reset index and update function.

**Comment by jamesrkg** [comment]
Resolved by #488.
