### ISSUE TITLE
add option to get response-based pct calculations.

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#490]
Normally all percentages calculations are based on respondents. The `raw_sum` parameter in the `Quantity.count()` method can help here.

**Comment by alextanski** [comment]
will be a basic known view called `res_c%`:
![image](https://cloud.githubusercontent.com/assets/13119448/15018181/d5accae6-1218-11e6-913a-e5609ada8323.png)

view key might be:
![image](https://cloud.githubusercontent.com/assets/13119448/15018206/ee123a44-1218-11e6-9ce2-83d0ba4504de.png)

**Comment by alextanski** [comment]
Need to fix:

1. pass over arrays Links that have `y!='@'`

**Comment by alextanski** [comment]
Basic implementation done, PR available. Creating new ticket for bugfixing, unsolved issues, etc.

**Comment by jamesrkg** [comment]
Resolved by #502.
