### ISSUE TITLE
dataset and engine missing handling: reverse key: value structure

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#496]
Instead of:
`(999, 777): 'exclude'`

it should be:
`'exclude': (999, 777)`

**Comment by alextanski** [comment]
This is in the codebase now, running a couple of tests:

*Missing map structure*:
`missmap = {'exclude': [955, 977],
		   'd.exclude': [999881, 1],
		   'LOLZ': [2, 3, 4]}`

dataset.set_missings('q14', missmap)

**Comment by jamesrkg** [comment]
Resolved by #498.
