### ISSUE TITLE
descriptives: buggy key-notation when excluding values and running multiple versions of stats on raw numeric data

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#499]
Since raw numerical columns do not have `values` meta, code exclusion cannot be reflected in the `condition` part of a view key notation. Therefore, multiple versions of a statistic with different edits might get overwritten.

To solve this we need an alternative way to express a condition on the values. Easiest would be something like this (yes I know that it clashes with complex logic)

`x|d.mean|x~[0]:|||ZCC_q17_2_1_1` for the exclusion of 0 from a raw numeric.

**Comment by alextanski** [comment]
`x|d.mean|x~{0}:|||ZCC_q17_2_1_1`

**Comment by jamesrkg** [comment]
Resolved by #505.
