### ISSUE TITLE
Cell Contents inconsistent when mean tests are included.

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#512]
The text should use only the significance level, so for example...
`Cell Contents (Column Percentages, Statistical Test Results), Statistics (Column Proportions,Means, (95%/5%): A/B,...)
`
would become...
`Cell Contents (Column Percentages, Statistical Test Results), Statistics (Column Proportions,Means, (5%): A/B,...)
`

**Comment by jamesrkg** [comment]
Resolved by #513.
