### ISSUE TITLE
read_dimensions: data column order bug

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#524]
Bug fix for placement of masks in `meta['sets']['data file']['items']` (_i520-readdimensions_mask_bugfix_) can lead to a mismtach in the order of the columns in the csv output from `read_dimensions()`, which in turn leads to invalid data when using `write_spss()`.

The csv output from `read_dimensions()` needs have a column order which matches `meta['sets']['data file']['items']`.

**Comment by jamesrkg** [comment]
Resolved by #525.
