### ISSUE TITLE
powerpoint painter UK specials

### ISSUE THREAD

**Issue by nitsrek** [Quantipy/quantipy#543]
Changes to UK-Hub only:

-automate front page
-shape dimensions adjusted
-grid name changed from ‘core_q5[{core_q5a}].core_q5_grid’ to ‘core_q5’
-net position in charts
-pipe through the project title to every slide

**Comment by nitsrek** [comment]
Done:
-automate front page
-pipe through the project title to every slide
need changes/additions in pptx_constants + constants (template)

-shape dimensions adjusted, also changes in pptx_constants + constants (template)

**Comment by nitsrek** [comment]
Done:
-grid name changed from ‘core_q5[{core_q5a}].core_q5_grid’ to ‘core_q5’
addition: pptx_constants -> key: 'short_grid_name'

**Comment by nitsrek** [comment]
Done:
-net position in charts
if there is a sorting nets are appended to fixed categories


All ready!

**Comment by nitsrek** [comment]
fixed an issue coming up when nets are included to fixed_categories (default_props['fixed_categories'] gets overwritten)

**Comment by jamesrkg** [comment]
Resolved by #558.
