### ISSUE TITLE
get_chain(): array summaries / should .content_of_axis automatically be modified to only contain @ ?

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#553]
get_chain() assumes one axis to be of fixed size and content, i.e. chains with an x-orientation are assumed to share the same y-axis. This is not true for array summaries, since they have an @-y-axis.

Strictly speaking, pulling multiple Chains with `get_chain(..., orientation='x', ...)` should ignore array summaries completely, since an array summary is not compatible with what is defined as a `Chain` .

**Comment by jamesrkg** [comment]
@alextanski agree, array summaries are a special case. We don't want to bend `get_chain()` out of shape for a minor low-level convenience.

**Comment by alextanski** [comment]
closing.
