### ISSUE TITLE
pptx_painter: does not work without meta['sets']['spec']

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#572]
Probably related to: #543 

`pptx_painter` assumes that the meta has a `spec` in the `sets` object. Related to that, there are assumptions about the meta and pptx layout/structure that will only be true when facing an Omnibus template scenario.

**Comment by nitsrek** [comment]
no changes in pptx_painter

preparing template: 
add meta['sets']['spec'] with data from "project.py"

**Comment by jamesrkg** [comment]
@nitsrek i'm closing this - sounds like it doesn't need a fix. If not please re-open.
