### ISSUE TITLE
tools.prep / DataSet: merge_meta func: ignores mask meta

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#574]
Two small bugs:
1. List compr. returns an empty list if two datasets contain the identical mask names.
2. If 1. is solved, text_key'ed meta is overwritten/replaced instead of updated.

**Comment by alextanski** [comment]
i will resolved this in within the branch for #571, so I am closing this.

**Comment by jamesrkg** [comment]
Resolved by #575.
