### ISSUE TITLE
DataSet: force_texts(name=None, copy_to=None, copy_from=None)

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#581]
DataSet should be able to copy over the `text` information from existing `text_key`s to a new one or update the existing one. This can be used to force empty/non-existing `text_key` information from another that is known.

If `name == None`: Run on all meta objects inside `masks` and `columns`. Otherwise just on the variable(s) given in `name` (which can be a list of names).

**Comment by nitsrek** [comment]
first draft implemented, unit-test needed

**Comment by jamesrkg** [comment]
Resolved by #588.
