### ISSUE TITLE
powerpoint painter drop nets from summary charts

### ISSUE THREAD

**Issue by nitsrek** [Quantipy/quantipy#585]
pptx needs option to include /exclude nets from array summary charts.

**Comment by nitsrek** [comment]
function (pptx painter) is modified, given parameter "inclued_nets" gets new option (e.g. "partly") -> nets are included, except for array summary charts

if German Omnibus decides for partly shown nets, changing in the template could be:
include_nets=False if is_nordic else 'partly' if is_de else True

**Comment by jamesrkg** [comment]
Resolved by #586.
