### ISSUE TITLE
DataSet: .validate() wanted!

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#596]
We really want to have a `validate()` method in the `DataSet` class that is going through the the document and checks that....

1. `array`, `single`, `delimited set` variables are well-formed meta objects, i.e. all required sub-objects are there.

2. All `text` objects are structured using `dict`s of `text_key` to text mapping.

3. The `DataSet.text_key` (default) is provided in all text objects.

4. Categorical data entries in the `._data` component have `values` metadata.

We can start this off by simply printing to screen what is wrong on which variable. Later this could be fine tuned into a summary output that is presenting the errors in a nice layout (maybe a pd.DataFrame).

Adding @jamesrkg only for thoughts/suggestions.

**Comment by alextanski** [comment]
we will have this in branch #605 (partly)

**Comment by nitsrek** [comment]
working on alternative solution that can be proved with unit-test

**Comment by nitsrek** [comment]
new version is commited.

needs unit test

**Comment by jamesrkg** [comment]
Resolved by #624.
