### ISSUE TITLE
DataSet.vmerge(): uniquify_key assumes a variable "datasource"

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#606]
I have not properly tidied this up after I thought I was done:

The new parameter to the `DataSet.vmerge()` implementation `uniquify_key` is calling `_make_unique_key()` with the `multiplier` param set to `'datasource'`. It should be called with `row_id_name`, however.

Also:
In the `_make_unique_key` method itself, the two error handlers in the beginning make no sense:
Both should simply test if...
1. ...the variables are inside the dataset
2. ...the variables are `int`-like (not necessarily meta-typed `int`). `single, int, float` are technically possible.

@nitsrek: Can you please fix my errors :-) !

**Comment by nitsrek** [comment]
changed error handlers and vmerge calls _make_unique_key() with row_id_name

**Comment by alextanski** [comment]
Thanks @nitsrek!
Picking this up in #607.

**Comment by jamesrkg** [comment]
Resolved by #607.
