### ISSUE TITLE
Mask items not correctly updating from the right

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#645]
When using `vmerge()`, if the left dataset has `N` items in a mask and the right dataset has `N+1` in the same mask then the the new element does appear in the `meta['columns']` but not in the list of mask items found in `meta['maks'][<mask name>]['items']`.

The new element should be appended to the `items` list so we respect the order found in the left dataset.

**Comment by AlasdairE** [comment]
Also, the item will be missing from `meta['sets'][<mask name>]['items']`

This also applies to any new values (categories). The new values from the right dataset will appear in `meta['columns'][<mask item>]['values']` but not `meta['lib']['valules'][<mask name>]`

**Comment by AlasdairE** [comment]
Similarly, any new values (categories) do not appear in `meta['lib']['values'][<mask name>]`

**Comment by nitsrek** [comment]
done

fixed in #629
