### ISSUE TITLE
dependency updates: update pandas, numpy, etc. and fix failing QP code

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#653]
We cannot longer wait to upgrade QP dependency libs.

**Comment by alextanski** [comment]
Next attempt.

**Comment by alextanski** [comment]
``scipy               0.18.1``
``numpy               1.11.3``
``numexpr             2.6.1``
``matplotlib          1.4.3``
``pandas              0.19.2``
``savReaderWriter     3.3.0``

**Comment by jamesrkg** [comment]
Resolved by #702.
