### ISSUE TITLE
DataSet: hiding/slicing - drill down to item level for arrays

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#673]
When called with the name of an array mask, the methods should apply the rules to the ``columns`` level meta of the array.

**Comment by alextanski** [comment]
We first need to think about what is different between ``rules`` on ``masks`` and ``rules`` on ``columns``:

- When we want to drop from an array, we must separate between values and items dropping.
- Do we want to allow different versions of a ``rule`` for different items of an ``array``?
- Do we want to have a hierarchy of rules, i.e. ``mask`` rules (for summaries, etc.) dominate ``column`` ``rules`` or do we want to allow for full flexibility?
- ...

**Comment by alextanski** [comment]
for 3.0

**Comment by nitsrek** [comment]
DataSet.hiding() has option to hide items or values
