### ISSUE TITLE
DataSet.meta(): should report column type for arrays, not "array"

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#687]
Currently ``.meta()`` will report ``array`` for the type of the variable meta, although it would make more sense to drill down to the items type.

**Comment by jamesrkg** [comment]
@alextanski should we take this opportunity to add a `subtype` for the `array` mask that stores this?

e.g.: 

```python
{
    "type": "array",
    "subtype": "delimited set",
    "items": [...],
    "text": {...}
}
```

**Comment by alextanski** [comment]
Looks like practical solution for the ``array`` type in my opinion (as the simplest of the complex data structures).

**Comment by alextanski** [comment]
picked up in #732
