### ISSUE TITLE
PowerpointPainter: base text control

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#695]
We need a method to modify the base text prefix `Base`.

This could be done with a new kwarg in the `slide_properties` arg called `'base_text'`, e.g.
```python
slide_properties = dict(
    shape_properties=NORDIC_SHAPE_PROPERTIES,
    pptx_template_name='YouGov_template.pptx',
    slide_layout_name='Mid_blank_with_header_footer',
    base_type_name='weighted',
    display_var_names=False,
    base_text='Bas'
)
```

If not included in `slide_properties` `dict` then the default `Base` would be used.

**Comment by jamesrkg** [comment]
Resolved by #696.
