### ISSUE TITLE
DataSet: derotate() array/mask method wanted

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#697]
We have a stand-alone version of a ``derotate()`` method that will level-transform case data. We need to include this into the set of ``DataSet`` array transformation methods (``transpose``, ``flatten``). Along the way, we also need to make sure to:

1. Write docs for it. There are already entries about ``transpose()`` and ``flatten()``.
2. Add the automatic creation of metadata and the ability to save the new ``DataSet`` components to ``.csv``/``.json``.
3. Auto-convert the levelled DataSet to SPSS ``.sav`` (Dims.?).
4. Include unittest(s)

**Comment by nitsrek** [comment]
solved in #703
