### ISSUE TITLE
read_dimensions: crashes when mdd has meta on columns that are not in the ddf 

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#705]
Currently, it is assumed that the `ddf` contains all columns listed in the `.mdd` metadata. This might not be the case and should not lead to data inconsistencies (while `ddf`s with columns not registered in the `mdd` would). We should catch these situations and report them while converting; right now the method will simply crash with a `KeyError`.

**Comment by jamesrkg** [comment]
Resolved by #709.
