### ISSUE TITLE
Function emulate_meta edits meta in place

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#711]
The methods that rely on `emulate_meta` should not result in a change to the meta, which can be confusing.
Either we only pass copies of meta (sub-meta) to `emulate_meta` or it creates copies.

**Comment by AlasdairE** [comment]
Re-opening issue for action when re-write of helper methods takes place.

**Comment by RoxanaMariaNeagu** [comment]
Closing ticket as the fix will come in the `dataset` method `crosstab`
