### ISSUE TITLE
Support for cumulative percentages for cell contents

### ISSUE THREAD

**Issue by AndersFreund** [Quantipy/quantipy#748]
Cumulative column percentages. Express the column percentages as cumulative percentages.
![image](https://cloud.githubusercontent.com/assets/23186359/24614887/f3994b80-188c-11e7-9895-c006b2f75a7b.png)

**Comment by alextanski** [comment]
picked up in #744 (thanks @nitsrek )

**Comment by alextanski** [comment]
Above is incorrect. This was done in a separate branch.

**Comment by jamesrkg** [comment]
Resolved by #754.
