### ISSUE TITLE
Dataset copy method creating incorrect column names

### ISSUE THREAD

**Issue by AlasdairE** [Quantipy/quantipy#749]
For example:
```python
dataset.copy('q1.q1_grid', 'ZZ')
```
creates column names such as `columns@q1_ZZ[{q1_ZZ_1}].q1_ZZ_grid` rather than `q1_ZZ[{q1_ZZ_2}].q1_ZZ_grid`

**Comment by jamesrkg** [comment]
Resolves by #750.
