### ISSUE TITLE
Method DataSet.crosstab need to copy meta

### ISSUE THREAD

**Issue by RoxanaMariaNeagu** [Quantipy/quantipy#774]
Currently `emulate_meta` will pull `values` from `meta['lib']['values']` for a mask into the mask item's column meta, so users will have a modified version of the meta after using some DataSet method `crosstab`

Proposed solution:
The dataset method will pass a copy of the meta to `quantipy.core.tools.dp.prep`

**Comment by jamesrkg** [comment]
Resolved by #775.
