### ISSUE TITLE
DOCS: All examples must use Example Data (A) and run in non-Dims. mode

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#779]

**Comment by alextanski** [comment]
@nitsrek: Prio.

**Comment by jamesrkg** [comment]
@nitsrek can you review to see where this got up to?

**Comment by jamesrkg** [comment]
https://github.com/Quantipy/quantipy/issues/781

**Comment by nitsrek** [comment]
examples look good: non-dims mode + Example Data (A) or fake/ randomized data is used
Docs in general are not up-to-date: only partly filled or sometimes outdated information included
