### ISSUE TITLE
wanted: DataSet.restore_item_texts() [as a counterpart to cut_item_texts()]

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#796]
And then we could add the ``restore_item_texts()`` method to ``repair()`` and also have an option for `pd.set_option()` called `'array_item_texts': {'short', 'full'}`

**Comment by alextanski** [comment]
@nitsrek: Prio.

**Comment by nitsrek** [comment]
DataSet.restore_item_texts() created in branch i796_restore_item_texts

@alextanski: option is not created

**Comment by nitsrek** [comment]
done and merged
