### ISSUE TITLE
DataSet method wanted: dichotomizing delimited sets

### ISSUE THREAD

**Issue by nitsrek** [Quantipy/quantipy#806]
use DataSet.make_dummy()

metadata has to be created

**Comment by alextanski** [comment]
@nitsrek: Prio.

**Comment by alextanski** [comment]
@nitsrek:
Your approach is better than using `make_dummy()`:
`for x in dataset.codes_in_data('Q3'):
	dataset.derive('Q3_{}'.format(x), 'single', dataset.text('Q3'),
	               [(1, '',  {'Q3': [x]})])`

**Comment by alextanski** [comment]
done with #840 i833
