### ISSUE TITLE
f.sum view method

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#81]
We need an ``f.sum`` view method that sums the the frequency of ``x`` by ``y`` along the given axis, such that ``f.sum:f|x:`` would create a row of column sums, and ``f:f.sum|:y`` a column of row sums.

For consistency these example view key notations use the proposed new-style notation rules explained in issue https://github.com/Quantipy/quantipy/issues/67. In this way ``f.sum`` would be a specialized version of ``f.math`` where all the operators were assumed to be ``+``.

However, the initial fix for this issue may use an older style if necessary, in which case the notation will migrate along with everything else when the new rules have been agreed.

**Comment by alextanski** [comment]
So is this simply a raw summation of counts in that sum(counts) = cbase if single and sum(counts) >= cbase for multi?

**Comment by jamesrkg** [comment]
Yes, that's right. As per "totalsum" in our Scandinavian output.

**Comment by jamesrkg** [comment]
This will be resolved by #290.
