### ISSUE TITLE
Applying custom base conditions to frequency views

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#83]
We need a way to apply conditions onto the implied base of frequency views so as to allow for fine control over proportional (%) results.

In effect, this is cusomization of the `kwarg` `rel_to`:

``` python
'rel_to': [
    None, 
    'y', 
    {'y': {'x': has_any(frange('1-8'))}}
]
```

In this case, three sets of views are created - counts, natural-c% and custom-c% using the additional logical condition `{'x': has_any(frange('1-8'))}`.

Custom `rel_to` instructions follow the convention `{axis_of_orientation: wildcard_logical_condition}` where `wildcard_logical_condition` can be any wildard custom logic with the added option of using the shorthand keys `x` or `y` to refer to the given link's `x` or `y` variables. This shorthand would only be available for non-nested link axes!

The view keys, respectively, would be (I'm using the view key notation proposed in #67):

`rel_to: None`  --> `x|f|:|||my_net`
`rel_to: 'y'`  --> `x|f|:|y||my_net`
`rel_to: {'y': {'x': has_any(frange('1-8'))}}`  --> `x|f|:|y:x[{1,2,3,4,5,6,7,8}]||my_net`

**Comment by alextanski** [comment]
I think we must turn the base def. into a part of a block net defintion to make this more flexible and easier to manage.

**Comment by alextanski** [comment]
Also: what we really need is a "rebaser" method that returns an array of column bases depending on a condition.
