### ISSUE TITLE
new Chains: must have features

### ISSUE THREAD

**Issue by alextanski** [Quantipy/quantipy#858]
* ~add auto-painting of "unweighted" vs. regular base~ *Done...*
* add method to access all meta / `properties` of file metadata on question per key
* ~auto-paint base text property~ / add as attribute

# --------------------------------------------------------------------------------

BUGS:

~* more than 26 letters, `reindex()` auto-sorts letter index so tests are in an undesired order...~

**Comment by AndersFreund** [comment]
In self.contents i am missing "is_sum" or "c_pct_sum" to be accurate, not sure if it have to be that specific.

**Comment by AndersFreund** [comment]
I could really use a boolean attribute: _is_painted_.
Set to True when method _Paint_ is called and inverted when _toggle_labels_ are called.

**Comment by alextanski** [comment]
``ChainManager._chains`` must allow ``{'some name': chain(s)}`` for folder-like structures.
