### ISSUE TITLE
Need a convenient way of exploding set/mask items for use with stack.add_link()

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#9]
It would be useful to have an easy, and preferably internal, way of using `stack.add_link()` when a list of items found in the definition of a set or mask is what's needed, rather than the named set or mask given to the `x` or `y` parameters..

A stack-external approach would be to provide a convenience function that takes a list of variable names and inspects it for sets/masks, replacing set/mask references with their exploded items lists instead.

An stack-internal approach would be to somehow tell the method if you wanted to explode sets/masks or keep their type untouched. A second option here would be to have different rules for how `stack.add_link()` handles sets vs masks (explodes one and not the other) but that may result in more user-management of the meta than desired (you don't really want to have to generate a set-version of a mask if it doesn't exist already just so you can use the set in `stack.add_link()` - in that situation it would be quicker to list-comprehend the exploded items out yourself).

**Comment by alextanski** [comment]
The prefered way to generate a ``Stack`` will be to use the ``DataSet`` / ``Batch`` ``.populate()`` command. ``Batch`` defintions are automatically unrolling masks (if desired) etc. Closing this.
