### ISSUE TITLE
(new) Chain annotations and ChainManager control for them

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#914]
Chain annotation control should move into the `ChainManager` since any build could potentially make use of them. We should be careful how we implement this because use cases are likely to expand over time. 

We need to support multiple categories of annotations (the dims model allows for 'header title', 'center', 'left side', 'right side', 'footer title', 'center', 'left side' and 'right side') and multiple annotations per category (not just a single string). Multiple annotations per category would allow for setting up multiple rows of annotations for a single category in the Excel tables. A single annotation category could be given as a single string but that should be converted to a single-item list for consistency.

Quantipy needs a default set of annotation categories (keys), such as:

```python
{
    "header-title": [...],
    "header-left": [...],
    "header-center": [...],
    "header-right": [...],
    "footer-title": [...],
    "footer-left": [...],
    "footer-center": [...],
    "footer-right": [...]
}
```

We should add a `ChainAnnotation` class inheriting from `defaultdict` to make using this simpler, otherwise the same code for working with it will end up being re-written for every build. Potentially, the class should only accept the expected annotation keys. 

```python
# key accessors
>>> chain.annotations['header-title']
[...]

>>> chain.annotations['footer-right']
[...]

# dotted accessors
>>> chain.annotations.header.title
[...]

>>> chain.annotations.footer.right
[...]

# list non-empty annotations (for easy iteration via key-accessors)
>>> chain.annotations.populated
["header-title", "footer-right"]

# easy iteration
>>> for key, annotation in chain.annotations.iteritems():
...     print key, annotation
'header-title' [...]
'footer-right' [...]

# convenient repr (showing only populated annotations
>>> print chain.annotations
Headers
- title: [...]
Footers
- right: [...]
```

The ChainManager will need to make it easy to get/set the annotations for its chains.

Firstly this should be supported with the addition of `.get_chains(..., annotations)`. Where there is only 1 x-key this `annotations` could be an instance of `ChainAnnotation` or a dict (as above) that can easily instantiate a `ChainAnnotation`. Where there is more than 1 x-key it must be a dict of the same keyed to those x-keys.

Getting/setting chain annotations for the chains in a populated `ChainManager` could also be done by referencing the x-key of the chains, but there's no guarantee currently that each x-key will in a ChainManager will be unique (since `.get_chain()` could be used multiple times). The chances that this would be the case are probably rare though so we could accept a failure in this case and direct the user to find the chain they're actually after manually and add the annotation to that chain directly.

**Comment by jamesrkg** [comment]
@AlasdairE

**Comment by alextanski** [comment]
I have added the basic Class for this (dict like, annotation types, __getitem__, __setitem__ overloading to restricted annotation keys, set_annotations(), etc.)

@jamesrkg 
Let's chat about how to connect with the `ChainManager` class in the contect of folders and general naming conventions.

**Comment by alextanski** [comment]
Done and merged.
