### ISSUE TITLE
(new) banked chains and ChainManager control for them

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#915]
A banked chain is a chain that results from concatenating multiple existing chains together. Typically this is done by taking only specific rows from each chain. There should be an assumption that the y-keys on each input chain are the same (banking chains with different y-keys makes no sense). An example of this is producing a mean summary from a series of chains. The result would be a single chain that only contains the required base rows plus the mean from each input chain.

The `ChainManager` needs to provide a mechanism for producing banked chain from some of its collection of chains. The ouput needs to be normal `Chain` instance that supports all processes that are dependent on chains. 

Problems to solve:
* how to identify multiple chains in the ChainManager (there is no guarantee that chain x-keys will be unique given `.get_chains()` could be used more than once to collect the same x-key).
* how to conveniently pick up the rows/views that are needed
* how to handle the base row/s (the chains may not have the same base and this may be important)
* how to ensure that all dependent processes will be supported (all ChainManager methods that work on a chain should work on a banked chain, builds should not have to know if it was banked, and so on)

**Comment by jamesrkg** [comment]
@AlasdairE

**Comment by alextanski** [comment]
I have started to work on this and we probably will end with up with a method `ChainManager['the folder here'].bank(bank_on, inplace=False)` that effectively builds a new `Chain`. First draft soon/toy example soon.

**Comment by alextanski** [comment]
This is all implemented via the `cut`/`join` now.
