### ISSUE TITLE
ChainManager: paint needs to deal with axis edits (labels/ texts)

### ISSUE THREAD

**Issue by nitsrek** [Quantipy/quantipy#942]
currently only flat axis edits can be handled:
text = {'en-GB': text,
            'x edits': text}
adding the parameter text_keys = {'x': ['x edits']} crashes in the translations

default text_objects in DataSet and Stack have the following format:
text = {'en-GB': text,
            'x edits': {
                    'en-GB': text}
            }

**Comment by AlasdairE** [comment]
Taken care of by i848
