### ISSUE TITLE
write_dimensions needs to allow control over date format

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#960]
`write_dimensions`  uses a standard version of `_create_ddf.dms` that includes the following function declaration in `OnNextCase`. In that function the split date string is interpreted in the following way:

```python
syear = date_parts[0]
smonth = date_parts[1]
sday = date_parts[2]
```

However, this is later parsed as:

```python
DateString = sday +" "+ smonth +" "+ syear +" "+ stime
```

Which assumes the original string is `DD/MM/YYYY`. For US dates it will instead be `MM/DD/YYYY`.

`write_dimensions` needs to allow control over what format to apply to the date strings being converted. It's likely this could be easily accomplished by adding a new constant to the top of the DMS such that:

```
#define DATE_FORMAT  "MMDD"

If DATE_FORMAT = "MMDD" Then
    DateString = smonth +" "+ sday +" "+ syear +" "+ stime
Else
    DateString = sday +" "+ smonth +" "+ syear +" "+ stime
End Uf
```

**Comment by alextanski** [comment]
done. fixed. merged.
