### ISSUE TITLE
Improvements/fixes for hmerging coding from Ascribe

### ISSUE THREAD

**Issue by jamesrkg** [Quantipy/quantipy#97]
``hmerge`` could use a few improvements related to how it deals with the ``pandas.DataFrame.merge`` parameters ``left_on``, ``right_on``, ``left_index`` and ``right_index``. Currently it's necessary to always set the ``left_on``/``right_on`` columns into the index of each dataframe and use ``left_index``/``right_index``.

There is also some unusual behavior happening with the resulting data being fed into ``stack.add_link()`` that should be investigated, though this may end up being caused by the user.

``index 2184784 is out of bounds for axis 0 with size 2111`` is the fatal error being returned by ``stack.add_link()`` and in this case 2184784 is one of the unique ids used in the merge.

**Comment by alextanski** [comment]
This is with 98% certainty a problem of the matrix and can be solved easily. The matrix assumes a re-indexed source data df that is indexed 0 to len(df.index). After the merge the index is probably and identity-like variable, the matrix tries to query the old index-position and says:no.

I think this can only happen when the merge is performed AFTER add_data() has been run.

**Comment by alextanski** [comment]
The problem is really on the cache, but the solution is still easy.

**Comment by jamesrkg** [comment]
Ok, thanks @alextanski, I'll ticket that separately and resolve the problem with ``hmerge`` here.
